using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using Autodesk.Revit.UI.Selection;
using MainProjectApi.Helper;

namespace MainProjectApi.ChangeSheetNumber
{
    [Transaction(TransactionMode.Manual)]
    public class ChangeSheetNumberBinding : IExternalCommand
    {
        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            UIApplication uiApp = commandData.Application;
            Document doc = uiApp.ActiveUIDocument.Document;
            //if (CheckAccess.CheckLicense() == true)
            //{
                AppPanelChangeSheetNumber.ShowFormChange();
            //}                
            return Result.Succeeded;
        }
    }
}
